const fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('app.js','utf8');
const market=fs.readFileSync('market-data.js','utf8');
const fail=message=>{throw new Error(message)};
const assert=(condition,message)=>{if(!condition)fail(message)};
const approx=(actual,expected,tolerance=0.02)=>assert(Math.abs(actual-expected)<=tolerance,`Expected ${expected}, got ${actual}`);
const start=app.indexOf('function attachmentFactor'),end=app.indexOf('function safeSheetText',start);
if(start<0||end<0)fail('Could not extract calculation block');
const context={Date,Intl,Blob,URL,console};vm.createContext(context);
vm.runInContext('const dec2=n=>Math.round((+n||0)*100)/100;const rub=n=>String(n);'+app.slice(start,end)+'\nthis.__api={attachmentFactor,itemNet,itemGross,periodsFromDates};',context);
const {attachmentFactor,itemNet,itemGross}=context.__api;
approx(attachmentFactor('2026-01-01','2026-01-31'),1);
approx(attachmentFactor('2026-01-01','2026-02-28'),2);
approx(attachmentFactor('2026-01-31','2026-02-28'),1.0322580645);
approx(attachmentFactor('2024-02-01','2024-02-29'),1);
const fullJan={start:'2026-01-01',end:'2026-01-31',rate:100000,qty:1,periods:1,extra:0,tax:0};
approx(itemNet(fullJan),100000);approx(itemGross(fullJan),100000);
approx(itemGross({...fullJan,tax:8}),108695.65217);
approx(itemNet({...fullJan,qty:2,extra:5000}),205000);
const safeLine=app.match(/^function safeSheetText\(value\).*$/m);
if(!safeLine)fail('safeSheetText not found');
vm.runInContext(safeLine[0]+';this.__safeSheetText=safeSheetText;',context);
const safeSheetText=context.__safeSheetText;
assert(safeSheetText('normal')==='normal','Normal spreadsheet text changed');
for(const payload of ['=HYPERLINK("https://example.com")',' +CMD()','\t=SUM(1,1)','\n@SUM(1,1)'])assert(safeSheetText(payload).startsWith("'"),`Spreadsheet payload not neutralized: ${JSON.stringify(payload)}`);
assert(!app.includes('window.print('),'Print-dialog PDF export returned');
assert(app.includes('workbook.xlsx.writeBuffer()'),'True XLSX export missing');
assert(app.includes('window.pdfMake.createPdf(doc).download'),'Direct PDF download missing');
assert(app.includes('location.protocol === "file:"'),'Local preview may send production analytics');
assert(!app.includes('class="avatar">АН'),'Authorization avatar returned');
assert(app.includes('https://t.me/filmres/7002'),'Direct StarDust/Filmres source link missing');
assert(!app.includes('https://t.me/filmres/7424'),'Incorrect StarDust/Filmres source link returned');
for(const post of ['7002','7222','7390'])assert((app+market).includes(`https://t.me/filmres/${post}`),`Direct Filmres post ${post} missing`);
assert(!market.includes('t.me/s/filmres?before='),'Paginated Telegram feed link returned');
assert(app.includes('data-feedback-topic="Хочу поделиться актуальной ставкой"'),'Rate-sharing topic is not preselected by its triggers');
assert(!app.includes('feedback-consent'),'Unrequested consent block returned to the feedback form');
const modalStart=app.indexOf('function modal('),modalEnd=app.indexOf('function render()',modalStart);
if(modalStart<0||modalEnd<0)fail('Could not extract feedback modal');
const modalContext={};vm.createContext(modalContext);
vm.runInContext('const assistantBar=()=>"";'+app.slice(modalStart,modalEnd)+';this.__modal=modal;',modalContext);
const rateModal=modalContext.__modal('feedback','Хочу поделиться актуальной ставкой');
assert(rateModal.includes('<option selected>Хочу поделиться актуальной ставкой</option>'),'Rate-sharing topic is not selected in feedback markup');
assert(!rateModal.includes('FormSubmit')&&!rateModal.includes('type="checkbox"'),'Consent/cookie copy leaked into feedback markup');
assert(rateModal.includes('required></textarea></label>'),'Feedback textarea is not closed correctly');
assert(!rateModal.includes('<dialog open'),'Feedback dialog bypasses native modal behavior');
assert(app.includes('dialog.showModal()'),'Feedback dialog does not use native modal behavior');
console.log('Core logic/security/form tests OK');
