const fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('app.js','utf8');
const fail=message=>{throw new Error(message)};
const assert=(condition,message)=>{if(!condition)fail(message)};
const approx=(actual,expected,tolerance=0.02)=>assert(Math.abs(actual-expected)<=tolerance,`Expected ${expected}, got ${actual}`);
const start=app.indexOf('function parseDate'),end=app.indexOf('// события',start);
if(start<0||end<0)fail('Could not extract calculation block');
const context={URL};vm.createContext(context);
vm.runInContext(app.slice(start,end)+'\nthis.__api={parseDate,monthlyProrata,calcEstimate};',context);
const {parseDate,monthlyProrata,calcEstimate}=context.__api;
approx(monthlyProrata(parseDate('2026-01-01'),parseDate('2026-12-31'),100000),1200000);
approx(monthlyProrata(parseDate('2026-01-01'),parseDate('2026-02-28'),100000),200000);
approx(monthlyProrata(parseDate('2026-01-31'),parseDate('2026-02-28'),100000),103225.80645);
approx(monthlyProrata(parseDate('2024-02-01'),parseDate('2024-02-29'),100000),100000);
const fullJan=calcEstimate({r:{unit:'месяц'},start:'2026-01-01',end:'2026-01-31',rate:100000,qty:1,people:1,tax:0});
approx(fullJan.period,1);approx(fullJan.net,100000);approx(fullJan.gross,100000);
const taxed=calcEstimate({r:{unit:'месяц'},start:'2026-01-01',end:'2026-01-31',rate:100000,qty:1,people:1,tax:.08});
approx(taxed.gross,108695.65217);
const safeLine=app.match(/^function safeSheetText\(value\).*$/m);
if(!safeLine)fail('safeSheetText not found');
vm.runInContext(safeLine[0]+';this.__safeSheetText=safeSheetText;',context);
const safeSheetText=context.__safeSheetText;
assert(safeSheetText('normal')==='normal','Normal spreadsheet text changed');
for(const payload of ['=HYPERLINK("https://example.com")',' +CMD()','\t=SUM(1,1)','\n@SUM(1,1)'])assert(safeSheetText(payload).startsWith("'"),`Spreadsheet payload not neutralized: ${JSON.stringify(payload)}`);
const helperStart=app.indexOf("const SAFE_UNITS="),helperEnd=app.indexOf("const fmt =",helperStart);
if(helperStart<0||helperEnd<0)fail('Security helper block not found');
vm.runInContext(app.slice(helperStart,helperEnd)+'\nthis.__sec={esc,safeExternalUrl,sanitizeCustomRecord};',context);
const {esc,safeExternalUrl,sanitizeCustomRecord}=context.__sec;
assert(safeExternalUrl('javascript:alert(1)')==='','javascript URL accepted');
assert(safeExternalUrl('http://example.com')==='','HTTP URL accepted');
assert(safeExternalUrl('https://example.com/').startsWith('https://'),'HTTPS URL rejected');
const custom=sanitizeCustomRecord({id:-1,dept:'Test',prof:'<img src=x onerror=alert(1)>',unit:'проект',amount:100});
assert(custom&&esc(custom.prof).includes('&lt;img'),'Custom record escaping regression');
console.log('Core logic/security tests OK');
