const fs=require('fs'),vm=require('vm');
const app=fs.readFileSync('app.js','utf8');
const market=fs.readFileSync('market-data.js','utf8');
const css=fs.readFileSync('app.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const fail=message=>{throw new Error(message)};
const assert=(condition,message)=>{if(!condition)fail(message)};
const approx=(actual,expected,tolerance=0.02)=>assert(Math.abs(actual-expected)<=tolerance,`Expected ${expected}, got ${actual}`);
const start=app.indexOf('function attachmentFactor'),end=app.indexOf('function safeSheetText',start);
if(start<0||end<0)fail('Could not extract calculation block');
const context={Date,Intl,Blob,URL,console};vm.createContext(context);
vm.runInContext('const dec2=n=>Math.round((+n||0)*100)/100;const rub=n=>String(n);const normalizeSearch=value=>String(value??"").toLocaleLowerCase("ru-RU").replaceAll("ё","е").trim();'+app.slice(start,end)+'\nthis.__api={attachmentFactor,itemNet,itemGross,periodsFromDates,usesAttachmentDates};',context);
const {attachmentFactor,itemNet,itemGross}=context.__api;
approx(attachmentFactor('2026-01-01','2026-01-31'),1);
approx(attachmentFactor('2026-01-01','2026-02-28'),2);
approx(attachmentFactor('2026-01-31','2026-02-28'),1.0322580645);
approx(attachmentFactor('2024-02-01','2024-02-29'),1);
const fullJan={unit:'месяц',start:'2026-01-01',end:'2026-01-31',rate:100000,qty:1,periods:1,extra:0,tax:0};
approx(itemNet(fullJan),100000);approx(itemGross(fullJan),100000);
approx(itemGross({...fullJan,tax:8}),108695.65217);
approx(itemNet({...fullJan,qty:2,extra:5000}),205000);
approx(itemNet({...fullJan,unit:'смена',periods:3}),300000);
assert(app.includes('usesAttachmentDates(x.unit) ? `<label>Дата прикрепления'),'Budget dates are not conditional on monthly units');
assert(app.includes('statusLabel(r.status, r)'),'Rate-aware letter-year status is not rendered');
assert(app.includes('statusTone(r.status)'),'Rate status colors are not derived from their semantic status');
assert(app.includes('scrollOpenedRateIntoView(openedRateId, restoreScrollY)'),'Mobile expanded-rate navigation does not restore the start of the opened row');
assert(app.includes('prefers-reduced-motion: reduce'),'Mobile expanded-rate scrolling ignores reduced-motion preference');
const scrollStart=app.indexOf('function scrollOpenedRateIntoView'),scrollEnd=app.indexOf('function drawRates',scrollStart);
if(scrollStart<0||scrollEnd<0)fail('Could not extract mobile expanded-rate scrolling');
let scrollTarget=null,scrollDuration=null;
const detailMain={getBoundingClientRect:()=>({top:500})};
const detailRow={classList:{contains:name=>name==='rate-detail-row'},querySelector:selector=>selector==='.inline-detail-main'?detailMain:null};
const scrollContext={window:{scrollY:900,matchMedia:(query)=>({matches:query.includes('max-width')}),scrollTo:(_x,y)=>{scrollContext.window.scrollY=y;}},document:{querySelectorAll:()=>[{dataset:{rateId:'42'},nextElementSibling:detailRow}],querySelector:selector=>selector==='.topbar'?{getBoundingClientRect:()=>({height:54})}:null},animatePageScrollTo:(target,duration)=>{scrollTarget=target;scrollDuration=duration;},requestAnimationFrame:(callback)=>callback()};
vm.createContext(scrollContext);vm.runInContext(app.slice(scrollStart,scrollEnd)+';scrollOpenedRateIntoView("42");',scrollContext);
assert(scrollTarget===1336&&scrollDuration===820,'Opened mobile rate does not scroll to the beginning of its expanded description below the sticky top bar');
const motionStart=app.indexOf('let pageScrollFrame'),motionEnd=app.indexOf('function scrollOpenedRateIntoView',motionStart);
if(motionStart<0||motionEnd<0)fail('Could not extract route scroll animation');
let motionTime=0,lastScrollY=null;
const motionContext={window:{scrollY:1000,innerHeight:800,matchMedia:()=>({matches:false}),scrollTo:(_x,y)=>{lastScrollY=y;}},document:{documentElement:{scrollHeight:2400}},performance:{now:()=>0},cancelAnimationFrame:()=>{},requestAnimationFrame:(callback)=>{motionTime+=170;callback(motionTime);return motionTime;}};
vm.createContext(motionContext);vm.runInContext(app.slice(motionStart,motionEnd)+';animatePageScrollTo(0);',motionContext);
approx(lastScrollY,0,0.01);
assert(app.includes('render(); animatePageScrollTo(0);'),'Route changes do not animate back to the page start');
const safeLine=app.match(/^function safeSheetText\(value\).*$/m);
if(!safeLine)fail('safeSheetText not found');
vm.runInContext(safeLine[0]+';this.__safeSheetText=safeSheetText;',context);
const safeSheetText=context.__safeSheetText;
assert(safeSheetText('normal')==='normal','Normal spreadsheet text changed');
for(const payload of ['=HYPERLINK("https://example.com")',' +CMD()','\t=SUM(1,1)','\n@SUM(1,1)'])assert(safeSheetText(payload).startsWith("'"),`Spreadsheet payload not neutralized: ${JSON.stringify(payload)}`);
assert(!app.includes('window.print('),'Print-dialog PDF export returned');
assert(app.includes('workbook.xlsx.writeBuffer()'),'True XLSX export missing');
assert(app.includes('window.pdfMake.createPdf(doc).download(exportName("pdf"))'),'PDF does not use PDFMake direct download');
assert(!app.includes('openPdfPreview')&&!app.includes('preview.location.replace(url)'),'File-protocol PDF export still depends on a popup/blob preview');
const pdfStart=app.indexOf('async function exportBudgetPdf'),pdfEnd=app.indexOf('function addCustomBudgetItem',pdfStart);
if(pdfStart<0||pdfEnd<0)fail('Could not extract PDF export');
let downloadedPdf='',pdfDocument=null;const pdfButton={textContent:'PDF',disabled:false};
const pdfContext={budgetItems:[{prof:'Режиссёр',dept:'Режиссёрский цех',unit:'смена',rate:100000,qty:1,periods:2,start:'',end:'',extra:0,tax:0}],$:()=>pdfButton,alert:message=>fail(message),ensurePdfMake:async()=>{},Intl,Date,dec2:value=>Math.round((+value||0)*100)/100,usesAttachmentDates:()=>false,attachmentFactor:()=>null,shortDate:()=>'',itemNet:x=>x.rate*x.qty*x.periods,itemGross:x=>x.rate*x.qty*x.periods,exportName:ext=>`budget.${ext}`,console,window:{pdfMake:{createPdf:doc=>{pdfDocument=doc;return{download:name=>{downloadedPdf=name}}}}}};
vm.createContext(pdfContext);vm.runInContext(app.slice(pdfStart,pdfEnd)+';this.__exportBudgetPdf=exportBudgetPdf;',pdfContext);
const pdfExportPromise=pdfContext.__exportBudgetPdf().then(()=>{assert(downloadedPdf==='budget.pdf','PDFMake direct download was not invoked');assert(pdfDocument?.pageSize==='A4','PDF document was not created');assert(pdfButton.disabled===false&&pdfButton.textContent==='PDF','PDF button did not recover after export');});
assert(app.includes('URL.revokeObjectURL(url), 60000'),'Object URL is revoked too early for slower mobile downloads');
assert(!app.includes('pdfMake?.vfs'),'PDFMake font readiness still relies on a removed public property');
assert(app.includes('pdfFontsReady = true'),'PDF font readiness is not tracked after the font bundle loads');
assert(app.includes('new URL("pdfmake.min.js", pdfAssetBase).href'),'PDFMake still depends on a third-party CDN at export time');
assert(app.includes('new URL("vfs_fonts.js", pdfAssetBase).href'),'PDF fonts still depend on a third-party CDN at export time');
assert(fs.existsSync('vendor/pdfmake.min.js')&&fs.existsSync('vendor/vfs_fonts.js'),'Vendored PDF runtime is incomplete');
assert(html.includes('vendor/pdfmake.min.js')&&html.includes('vendor/vfs_fonts.js'),'PDF runtime is not preloaded before the app');
assert(html.indexOf('vendor/vfs_fonts.js')<html.indexOf('app.js?v='),'PDF runtime loads after the application');
assert(app.includes('location.protocol === "file:"'),'Local preview may send production analytics');
assert(app.includes('function consentValue() { if (location.protocol === "file:") return null;'),'Local preview can permanently suppress its analytics-consent test banner');
assert(!app.includes('class="avatar">АН'),'Authorization avatar returned');
assert((app+market).includes('https://t.me/filmres/7002'),'Direct StarDust/Filmres source link missing');
assert(!app.includes('https://t.me/filmres/7424'),'Incorrect StarDust/Filmres source link returned');
for(const post of ['7002','7222','7390'])assert((app+market).includes(`https://t.me/filmres/${post}`),`Direct Filmres post ${post} missing`);
assert(!market.includes('t.me/s/filmres?before='),'Paginated Telegram feed link returned');
assert(app.includes('data-feedback-topic="Хочу поделиться актуальной ставкой"'),'Rate-sharing topic is not preselected by its triggers');
assert(!app.includes('feedback-consent'),'Unrequested consent block returned to the feedback form');
const modalStart=app.indexOf('function modal('),modalEnd=app.indexOf('function render()',modalStart);
if(modalStart<0||modalEnd<0)fail('Could not extract feedback modal');
const modalContext={};vm.createContext(modalContext);
vm.runInContext('const assistantBar=()=>"";'+app.slice(modalStart,modalEnd)+';this.__modal=modal;',modalContext);
const rateModal=modalContext.__modal('feedback','Хочу поделиться актуальной ставкой');
assert(rateModal.includes('<option selected>Хочу поделиться актуальной ставкой</option>'),'Rate-sharing topic is not selected in feedback markup');
assert(!rateModal.includes('FormSubmit')&&!rateModal.includes('type="checkbox"'),'Consent/cookie copy leaked into feedback markup');
assert(rateModal.includes('required></textarea></label>'),'Feedback textarea is not closed correctly');
assert(!rateModal.includes('<dialog open'),'Feedback dialog bypasses native modal behavior');
assert(app.includes('dialog.showModal()'),'Feedback dialog does not use native modal behavior');
assert(!app.includes('Данные актуальны'),'Unclear global data-status badge returned');
assert(!app.includes('market-source-strip'),'Removed market link strip returned');
assert(app.includes('<span>Цеха</span>'),'About metrics use the wrong workshop label');
assert(market.includes("id:'mpk-regions-2025'")&&market.includes('ELEMENT_ID=57863'),'Regional market card or its source is missing');
for(const section of ['Operatori','Zvukorezhisseri','RezhisseriMontazha','HudozhnikiPostanovschiki','Stsenaristi'])assert(market.includes(`/#${section}`),`Kinopoisk native section link is missing: ${section}`);
for(const tone of ['current','previous','market','archive','unpublished'])assert(css.includes(`.status.${tone}`),`Rate status palette is missing: ${tone}`);
assert(css.includes('.registry-page{overflow-anchor:none}'),'Mobile browser scroll anchoring can fight expanded-row navigation');
assert(css.includes('.rate-detail-row{scroll-margin-top:66px}'),'Mobile expanded detail can be hidden beneath the sticky top bar');
assert(css.includes('view-enter .42s cubic-bezier(.16,1,.3,1)'),'Page transitions do not use the intended eased motion');
assert(css.includes('html{scroll-behavior:auto}'),'Native smooth scrolling conflicts with the custom eased route animation');
pdfExportPromise.then(()=>console.log('Core logic/security/form tests OK')).catch(error=>{console.error(error);process.exitCode=1;});
